In [2]:
import pandas as pd
import numpy as np
import math
import re
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from surprise import Reader, Dataset, SVD
from surprise.model_selection import KFold
from surprise.model_selection import cross_validate

In [17]:
ratings=pd.read_excel('forncfitems.xlsx')

In [18]:
ratings

                            name                   asin  rating
0             32565748-000000000  Автомобильные колонки       1
1             32565748-000000000          Весы кухонные       1
2             32565748-000000000   Внешние аккумуляторы       1
3             32565748-000000000                Вытяжки       1
4             32565748-000000000           Игровые мыши       1
...                          ...                    ...     ...
166290   57565350-49485256515193  Чайники электрические       1
166291   57565352-52575050555092   Внешние аккумуляторы       1
166292   57565355-57554952485597               Мониторы       1
166293   57565355-57554952485597        Скамьи и стойки       1
166294  6103109_gm27@outlook.com          Электробритвы       1

[166295 rows x 3 columns]

In [19]:
matrix=pd.pivot_table(data=ratings[['name', 'asin', 'rating']], values='rating', index='name',columns='asin')
matrix = matrix.fillna(0)
matrix

asin,3D очки,3D принтеры,3D телевизоры,4K Ultra HD телевизоры,AV-ресиверы,Apple iPad,Apple iPhone,Blu-Ray плееры,Bluetooth и Wi-Fi адаптеры,Bluetooth-гарнитуры,...,Электромобили,Электронные книги,"Электроножи, электрооткрывалки",Электропилы,Электрорубанки,Электрошашлычницы,Эллиптические тренажеры,Эпиляторы,Эспандеры,"Ящики, органайзеры, сумки для инструмента"
name,,,,,,,,,,,,,,,,,,,,,
32565748-000000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32565748-535549565054 5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32565750-575448565151 а,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32565750-575448565151 а5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43553240-575054413251+7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57555656-55575253555698,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57565350-49485256515193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57565352-52575050555092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57565355-57554952485597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6103109_gm27@outlook.com,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
svd = SVD()
reader = Reader()
data = Dataset.load_from_df(ratings[['name', 'asin', 'rating']], reader)
cross_validate(svd, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.0174  0.0176  0.0174  0.0177  0.0178  0.0176  0.0002
MAE (testset)     0.0046  0.0047  0.0046  0.0047  0.0046  0.0046  0.0001
Fit time          8.77    7.78    7.01    6.99    7.13    7.54    0.68
Test time         0.19    0.31    0.21    0.16    0.27    0.23    0.06

{'test_rmse': array([0.01736664, 0.01762803, 0.01738528, 0.01772205, 0.01778875]),
 'test_mae': array([0.00461097, 0.00474258, 0.00455606, 0.00467603, 0.00464335]),
 'fit_time': (8.773122072219849,
  7.779116153717041,
  7.009474039077759,
  6.993019104003906,
  7.128602981567383),
 'test_time': (0.18552136421203613,
  0.31491541862487793,
  0.21390986442565918,
  0.16269254684448242,
  0.27228212356567383)}

In [21]:
trainset = data.build_full_trainset()
svd.fit(trainset)

In [22]:
def hybrid_recommendations(userId, productId):
    top_five=matrix.corrwith(matrix[productId]).sort_values(ascending=False).head(5)
    
    est_rating=[]
    for x in list(top_five.index):
        if str(top_five[x])!='nan':
            est_rating.append(svd.predict(userId, iid=x, r_ui=None).est)
           
    return pd.DataFrame({'productId':list(top_five.index)[:len(est_rating)], 'estimated_rating':est_rating}).sort_values(by='estimated_rating', ascending=False).reset_index(drop=True)

In [43]:
def all_hybrid_recommendations(userId):
    
    top_five=matrix.corrwith(matrix['Смартфоны'])
    
    est_rating=[]
    for x in list(top_five.index):
        est_rating.append(svd.predict(userId, iid=x, r_ui=None).est)
           
    return pd.DataFrame({'productId':list(top_five.index)[:len(est_rating)], 'estimated_rating':est_rating}).sort_values(by='estimated_rating', ascending=False).reset_index(drop=True)

In [44]:
find_product = hybrid_recommendations('32565748-000000000', 'Смартфоны')

def product_mapping(recommender_df): 
    rows_list = []
    rows_list2 = []

    for x in recommender_df['productId']:
        cut_row = ratings.loc[ratings['asin'] == x]
        cut_row = cut_row['asin'][0:1].values
        rows_list.append(cut_row[0])

    for i in recommender_df['estimated_rating']:
        rows_list2.append(i)

    cut_dict = {"product": rows_list, "estimated_rating": rows_list2}
    cut_df = pd.DataFrame(cut_dict)
    
    return cut_df

product_mapping(find_product)

               product  estimated_rating
0      Защитные стекла          1.107617
1      Защитные пленки          1.061907
2         Карты памяти          1.001004
3            Смартфоны          1.000296
4  Чехлы для телефонов          1.000000

In [45]:
find_all_product = all_hybrid_recommendations('32565748-000000000')

product_mapping(find_all_product).head(5)

                 product  estimated_rating
0           Кабельное ТВ          1.272936
1               Самовары          1.252560
2    Статуэтки и фигурки          1.239766
3         Фужеры и рюмки          1.233561
4  Косметические приборы          1.219338